spring:
  application:
    name: TIME-OFF-TRACKER
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://postgres:5432/time-off-tracker # url: jdbc:postgresql://postgres:5432/time-off-tracker
    username: postgres
    password: postgres # postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
default:
  user:
    email: admin
    password: admin
server:
  port: 8080
